namespace ClaudeSwitch.Core;

/// <summary>
/// Tiny runtime localization. <see cref="T"/> looks up the current language, falling back to
/// English and finally to the key itself, so a partially-translated language never shows blanks.
///
/// The chrome (buttons, labels, settings, menus) is translated into every listed language.
/// Long transient status/error strings are English-only and fall back gracefully.
/// </summary>
internal static class Loc
{
    public readonly record struct Language(string Code, string Name);

    /// <summary>Selectable languages, in menu order.</summary>
    public static readonly Language[] Languages =
    [
        new("en", "English"),
        new("tr", "Türkçe"),
        new("de", "Deutsch"),
        new("es", "Español"),
        new("fr", "Français"),
        new("ru", "Русский"),
        new("zh", "中文"),
    ];

    /// <summary>Raised after the language changes so open windows can re-render.</summary>
    public static event Action? Changed;

    private static string _lang = "en";

    public static string Current
    {
        get => _lang;
        set
        {
            var code = value?.ToLowerInvariant() ?? "en";
            if (!_table.ContainsKey(code)) code = "en";
            if (_lang == code) return;
            _lang = code;
            Changed?.Invoke();
        }
    }

    public static string CurrentName =>
        Languages.FirstOrDefault(l => l.Code == _lang).Name ?? "English";

    /// <summary>Localized string for <paramref name="key"/>, formatted with <paramref name="args"/>.</summary>
    public static string T(string key, params object[] args)
    {
        var s = Lookup(key);
        return args.Length == 0 ? s : string.Format(s, args);
    }

    private static string Lookup(string key)
    {
        if (_table.TryGetValue(_lang, out var t) && t.TryGetValue(key, out var v)) return v;
        if (_table["en"].TryGetValue(key, out var en)) return en;
        return key;
    }

    // ── translations ──────────────────────────────────────────────────────────
    // English is the base/fallback. Other languages translate the chrome keys.

    private static readonly Dictionary<string, Dictionary<string, string>> _table = new()
    {
        ["en"] = new()
        {
            ["app.loading"] = "Loading…",
            ["app.notSignedIn"] = "Not signed in",
            ["app.activePrefix"] = "Active: {0}",
            ["tip.refresh"] = "Refresh usage",
            ["tip.settings"] = "Settings",
            ["tip.more"] = "More",
            ["card.switch"] = "Switch",
            ["card.active"] = "Active",
            ["usage.fiveHour"] = "5-hour",
            ["usage.sevenDay"] = "7-day",
            ["usage.tooltip"] = "Real subscription usage — from the same source as Claude Code's /usage command (api.anthropic.com/api/oauth/usage). Covers usage across all devices and surfaces.\n\nOnly the active account updates live; others show their value from when they were last active. If the data can't be fetched, no percentage is shown.",
            ["usage.fetching"] = "fetching usage…",
            ["usage.updatesOnSwitch"] = "updates when you switch to it",
            ["usage.justNow"] = "just now",
            ["usage.minAgo"] = "{0}m ago",
            ["usage.hourAgo"] = "{0}h ago",
            ["usage.dayAgo"] = "{0}d ago",
            ["usage.updatedPrefix"] = "updated {0}",
            ["usage.resetting"] = "resetting…",
            ["usage.resetsInHM"] = "in {0}h {1}m",
            ["usage.resetsInM"] = "in {0}m",
            ["usage.resetsPrefix"] = "resets {0}",
            ["status.ready"] = "Ready",
            ["status.tokenWillRefresh"] = "Token will refresh",
            ["reauth.subtitle"] = "⚠ Sign-in expired — use \"+ Add Account\" to fix",
            ["empty.title"] = "No saved accounts yet",
            ["empty.body"] = "Save the account you're signed into, then add another to switch between them.",
            ["footer.saveCurrent"] = "Save current account",
            ["footer.addAccount"] = "+ Add Account",
            ["footer.cancel"] = "Cancel",
            ["code.title"] = "Paste the authorization code",
            ["code.body"] = "After clicking Authorize in the browser, paste the code shown on the page. This is not the 6-digit code sent to your e-mail.",
            ["code.submit"] = "Submit",
            ["menu.rename"] = "Rename",
            ["menu.refreshTokens"] = "Refresh this account's tokens",
            ["menu.refreshTokensTip"] = "Active account only: rewrites the live tokens into the profile.",
            ["menu.delete"] = "Delete profile",
            ["dialog.rename.label"] = "Display name",
            ["common.cancel"] = "Cancel",
            ["common.save"] = "Save",
            ["tray.noAccounts"] = "No saved accounts",
            ["tray.manage"] = "Manage accounts…",
            ["tray.exit"] = "Exit",
            ["settings.title"] = "Settings",
            ["settings.appearance"] = "APPEARANCE",
            ["settings.darkMode"] = "Dark mode",
            ["settings.darkModeDesc"] = "Use a dark color theme.",
            ["settings.compact"] = "Compact mode",
            ["settings.compactDesc"] = "Hide usage details for a denser list.",
            ["settings.language"] = "LANGUAGE",
            ["settings.languageDesc"] = "Interface language.",
            ["settings.done"] = "Done",
        },

        ["tr"] = new()
        {
            ["app.loading"] = "Yükleniyor…",
            ["app.notSignedIn"] = "Giriş yapılmamış",
            ["app.activePrefix"] = "Aktif: {0}",
            ["tip.refresh"] = "Kullanımı yenile",
            ["tip.settings"] = "Ayarlar",
            ["tip.more"] = "Diğer",
            ["card.switch"] = "Geç",
            ["card.active"] = "Aktif",
            ["usage.fiveHour"] = "5 saat",
            ["usage.sevenDay"] = "7 gün",
            ["usage.tooltip"] = "Gerçek abonelik kullanımı — Claude Code'un /usage komutuyla aynı kaynaktan (api.anthropic.com/api/oauth/usage). Tüm cihaz ve yüzeylerdeki kullanımı kapsar.\n\nYalnızca aktif hesap canlı güncellenir; diğerleri en son aktif olduğu değeri gösterir. Veri alınamazsa yüzde gösterilmez.",
            ["usage.fetching"] = "kullanım alınıyor…",
            ["usage.updatesOnSwitch"] = "geçince güncellenir",
            ["usage.justNow"] = "az önce",
            ["usage.minAgo"] = "{0} dk önce",
            ["usage.hourAgo"] = "{0} sa önce",
            ["usage.dayAgo"] = "{0} gün önce",
            ["usage.updatedPrefix"] = "güncelleme: {0}",
            ["usage.resetting"] = "sıfırlanıyor…",
            ["usage.resetsInHM"] = "{0} sa {1} dk sonra",
            ["usage.resetsInM"] = "{0} dk sonra",
            ["usage.resetsPrefix"] = "sıfırlanma: {0}",
            ["status.ready"] = "Hazır",
            ["status.tokenWillRefresh"] = "Token yenilenecek",
            ["reauth.subtitle"] = "⚠ Giriş süresi doldu — \"+ Hesap Ekle\" ile düzeltin",
            ["empty.title"] = "Henüz kayıtlı hesap yok",
            ["empty.body"] = "Giriş yaptığınız hesabı kaydedin, sonra geçiş yapmak için başka bir hesap ekleyin.",
            ["footer.saveCurrent"] = "Mevcut hesabı kaydet",
            ["footer.addAccount"] = "+ Hesap Ekle",
            ["footer.cancel"] = "İptal",
            ["code.title"] = "Yetkilendirme kodunu yapıştırın",
            ["code.body"] = "Tarayıcıda Authorize'a bastıktan sonra sayfada çıkan kodu buraya yapıştırın. Bu, e-postaya gelen 6 haneli kod değildir.",
            ["code.submit"] = "Gönder",
            ["menu.rename"] = "Yeniden adlandır",
            ["menu.refreshTokens"] = "Bu hesabın tokenlarını tazele",
            ["menu.refreshTokensTip"] = "Yalnızca aktif hesap: canlı tokenları profile yeniden yazar.",
            ["menu.delete"] = "Profili sil",
            ["dialog.rename.label"] = "Görünen ad",
            ["common.cancel"] = "Vazgeç",
            ["common.save"] = "Kaydet",
            ["tray.noAccounts"] = "Kayıtlı hesap yok",
            ["tray.manage"] = "Hesapları yönet…",
            ["tray.exit"] = "Çıkış",
            ["settings.title"] = "Ayarlar",
            ["settings.appearance"] = "GÖRÜNÜM",
            ["settings.darkMode"] = "Karanlık mod",
            ["settings.darkModeDesc"] = "Koyu renk temasını kullan.",
            ["settings.compact"] = "Sıkışık mod",
            ["settings.compactDesc"] = "Daha yoğun bir liste için kullanım ayrıntılarını gizle.",
            ["settings.language"] = "DİL",
            ["settings.languageDesc"] = "Arayüz dili.",
            ["settings.done"] = "Tamam",
        },

        ["de"] = new()
        {
            ["app.loading"] = "Wird geladen…",
            ["app.notSignedIn"] = "Nicht angemeldet",
            ["app.activePrefix"] = "Aktiv: {0}",
            ["tip.refresh"] = "Nutzung aktualisieren",
            ["tip.settings"] = "Einstellungen",
            ["tip.more"] = "Mehr",
            ["card.switch"] = "Wechseln",
            ["card.active"] = "Aktiv",
            ["usage.fiveHour"] = "5 Std.",
            ["usage.sevenDay"] = "7 Tage",
            ["usage.tooltip"] = "Echte Abonnement-Nutzung — aus derselben Quelle wie der /usage-Befehl von Claude Code (api.anthropic.com/api/oauth/usage). Umfasst die Nutzung auf allen Geräten.\n\nNur das aktive Konto wird live aktualisiert; andere zeigen den letzten aktiven Wert. Ohne Daten wird kein Prozentsatz angezeigt.",
            ["usage.fetching"] = "Nutzung wird geladen…",
            ["usage.updatesOnSwitch"] = "wird beim Wechsel aktualisiert",
            ["usage.justNow"] = "gerade eben",
            ["usage.minAgo"] = "vor {0} Min.",
            ["usage.hourAgo"] = "vor {0} Std.",
            ["usage.dayAgo"] = "vor {0} T.",
            ["usage.updatedPrefix"] = "aktualisiert {0}",
            ["usage.resetting"] = "wird zurückgesetzt…",
            ["usage.resetsInHM"] = "in {0} Std. {1} Min.",
            ["usage.resetsInM"] = "in {0} Min.",
            ["usage.resetsPrefix"] = "Zurücksetzung {0}",
            ["status.ready"] = "Bereit",
            ["status.tokenWillRefresh"] = "Token wird erneuert",
            ["reauth.subtitle"] = "⚠ Anmeldung abgelaufen — mit \"+ Konto hinzufügen\" beheben",
            ["empty.title"] = "Noch keine Konten gespeichert",
            ["empty.body"] = "Speichern Sie das angemeldete Konto und fügen Sie ein weiteres hinzu, um zu wechseln.",
            ["footer.saveCurrent"] = "Aktuelles Konto speichern",
            ["footer.addAccount"] = "+ Konto hinzufügen",
            ["footer.cancel"] = "Abbrechen",
            ["code.title"] = "Autorisierungscode einfügen",
            ["code.body"] = "Nachdem Sie im Browser auf Autorisieren geklickt haben, fügen Sie den angezeigten Code hier ein. Das ist nicht der 6-stellige Code aus der E-Mail.",
            ["code.submit"] = "Senden",
            ["menu.rename"] = "Umbenennen",
            ["menu.refreshTokens"] = "Tokens dieses Kontos erneuern",
            ["menu.refreshTokensTip"] = "Nur aktives Konto: schreibt die aktuellen Tokens ins Profil.",
            ["menu.delete"] = "Profil löschen",
            ["dialog.rename.label"] = "Anzeigename",
            ["common.cancel"] = "Abbrechen",
            ["common.save"] = "Speichern",
            ["tray.noAccounts"] = "Keine gespeicherten Konten",
            ["tray.manage"] = "Konten verwalten…",
            ["tray.exit"] = "Beenden",
            ["settings.title"] = "Einstellungen",
            ["settings.appearance"] = "DARSTELLUNG",
            ["settings.darkMode"] = "Dunkler Modus",
            ["settings.darkModeDesc"] = "Dunkles Farbschema verwenden.",
            ["settings.compact"] = "Kompaktmodus",
            ["settings.compactDesc"] = "Nutzungsdetails für eine dichtere Liste ausblenden.",
            ["settings.language"] = "SPRACHE",
            ["settings.languageDesc"] = "Sprache der Oberfläche.",
            ["settings.done"] = "Fertig",
        },

        ["es"] = new()
        {
            ["app.loading"] = "Cargando…",
            ["app.notSignedIn"] = "Sin iniciar sesión",
            ["app.activePrefix"] = "Activa: {0}",
            ["tip.refresh"] = "Actualizar uso",
            ["tip.settings"] = "Ajustes",
            ["tip.more"] = "Más",
            ["card.switch"] = "Cambiar",
            ["card.active"] = "Activa",
            ["usage.fiveHour"] = "5 horas",
            ["usage.sevenDay"] = "7 días",
            ["usage.tooltip"] = "Uso real de la suscripción — de la misma fuente que el comando /usage de Claude Code (api.anthropic.com/api/oauth/usage). Incluye el uso en todos los dispositivos.\n\nSolo la cuenta activa se actualiza en vivo; las demás muestran su último valor activo. Si no hay datos, no se muestra porcentaje.",
            ["usage.fetching"] = "obteniendo uso…",
            ["usage.updatesOnSwitch"] = "se actualiza al cambiar a ella",
            ["usage.justNow"] = "ahora mismo",
            ["usage.minAgo"] = "hace {0} min",
            ["usage.hourAgo"] = "hace {0} h",
            ["usage.dayAgo"] = "hace {0} d",
            ["usage.updatedPrefix"] = "actualizado {0}",
            ["usage.resetting"] = "reiniciando…",
            ["usage.resetsInHM"] = "en {0} h {1} min",
            ["usage.resetsInM"] = "en {0} min",
            ["usage.resetsPrefix"] = "reinicio {0}",
            ["status.ready"] = "Lista",
            ["status.tokenWillRefresh"] = "El token se renovará",
            ["reauth.subtitle"] = "⚠ Sesión caducada — usa \"+ Añadir cuenta\" para arreglarlo",
            ["empty.title"] = "Aún no hay cuentas guardadas",
            ["empty.body"] = "Guarda la cuenta con la que iniciaste sesión y añade otra para alternar entre ellas.",
            ["footer.saveCurrent"] = "Guardar cuenta actual",
            ["footer.addAccount"] = "+ Añadir cuenta",
            ["footer.cancel"] = "Cancelar",
            ["code.title"] = "Pega el código de autorización",
            ["code.body"] = "Tras pulsar Authorize en el navegador, pega aquí el código que aparece en la página. No es el código de 6 dígitos del correo.",
            ["code.submit"] = "Enviar",
            ["menu.rename"] = "Renombrar",
            ["menu.refreshTokens"] = "Renovar los tokens de esta cuenta",
            ["menu.refreshTokensTip"] = "Solo la cuenta activa: reescribe los tokens actuales en el perfil.",
            ["menu.delete"] = "Eliminar perfil",
            ["dialog.rename.label"] = "Nombre visible",
            ["common.cancel"] = "Cancelar",
            ["common.save"] = "Guardar",
            ["tray.noAccounts"] = "Sin cuentas guardadas",
            ["tray.manage"] = "Gestionar cuentas…",
            ["tray.exit"] = "Salir",
            ["settings.title"] = "Ajustes",
            ["settings.appearance"] = "APARIENCIA",
            ["settings.darkMode"] = "Modo oscuro",
            ["settings.darkModeDesc"] = "Usar un tema de color oscuro.",
            ["settings.compact"] = "Modo compacto",
            ["settings.compactDesc"] = "Ocultar los detalles de uso para una lista más densa.",
            ["settings.language"] = "IDIOMA",
            ["settings.languageDesc"] = "Idioma de la interfaz.",
            ["settings.done"] = "Listo",
        },

        ["fr"] = new()
        {
            ["app.loading"] = "Chargement…",
            ["app.notSignedIn"] = "Non connecté",
            ["app.activePrefix"] = "Actif : {0}",
            ["tip.refresh"] = "Actualiser l'usage",
            ["tip.settings"] = "Paramètres",
            ["tip.more"] = "Plus",
            ["card.switch"] = "Changer",
            ["card.active"] = "Actif",
            ["usage.fiveHour"] = "5 heures",
            ["usage.sevenDay"] = "7 jours",
            ["usage.tooltip"] = "Usage réel de l'abonnement — même source que la commande /usage de Claude Code (api.anthropic.com/api/oauth/usage). Couvre l'usage sur tous les appareils.\n\nSeul le compte actif est mis à jour en direct ; les autres affichent leur dernière valeur active. Sans données, aucun pourcentage n'est affiché.",
            ["usage.fetching"] = "récupération de l'usage…",
            ["usage.updatesOnSwitch"] = "mis à jour au changement",
            ["usage.justNow"] = "à l'instant",
            ["usage.minAgo"] = "il y a {0} min",
            ["usage.hourAgo"] = "il y a {0} h",
            ["usage.dayAgo"] = "il y a {0} j",
            ["usage.updatedPrefix"] = "mis à jour {0}",
            ["usage.resetting"] = "réinitialisation…",
            ["usage.resetsInHM"] = "dans {0} h {1} min",
            ["usage.resetsInM"] = "dans {0} min",
            ["usage.resetsPrefix"] = "réinit. {0}",
            ["status.ready"] = "Prêt",
            ["status.tokenWillRefresh"] = "Le jeton sera renouvelé",
            ["reauth.subtitle"] = "⚠ Connexion expirée — utilisez « + Ajouter un compte »",
            ["empty.title"] = "Aucun compte enregistré",
            ["empty.body"] = "Enregistrez le compte connecté, puis ajoutez-en un autre pour basculer entre eux.",
            ["footer.saveCurrent"] = "Enregistrer le compte actuel",
            ["footer.addAccount"] = "+ Ajouter un compte",
            ["footer.cancel"] = "Annuler",
            ["code.title"] = "Collez le code d'autorisation",
            ["code.body"] = "Après avoir cliqué sur Authorize dans le navigateur, collez ici le code affiché. Ce n'est pas le code à 6 chiffres reçu par e-mail.",
            ["code.submit"] = "Envoyer",
            ["menu.rename"] = "Renommer",
            ["menu.refreshTokens"] = "Renouveler les jetons de ce compte",
            ["menu.refreshTokensTip"] = "Compte actif uniquement : réécrit les jetons actuels dans le profil.",
            ["menu.delete"] = "Supprimer le profil",
            ["dialog.rename.label"] = "Nom affiché",
            ["common.cancel"] = "Annuler",
            ["common.save"] = "Enregistrer",
            ["tray.noAccounts"] = "Aucun compte enregistré",
            ["tray.manage"] = "Gérer les comptes…",
            ["tray.exit"] = "Quitter",
            ["settings.title"] = "Paramètres",
            ["settings.appearance"] = "APPARENCE",
            ["settings.darkMode"] = "Mode sombre",
            ["settings.darkModeDesc"] = "Utiliser un thème de couleur sombre.",
            ["settings.compact"] = "Mode compact",
            ["settings.compactDesc"] = "Masquer les détails d'usage pour une liste plus dense.",
            ["settings.language"] = "LANGUE",
            ["settings.languageDesc"] = "Langue de l'interface.",
            ["settings.done"] = "Terminé",
        },

        ["ru"] = new()
        {
            ["app.loading"] = "Загрузка…",
            ["app.notSignedIn"] = "Вход не выполнен",
            ["app.activePrefix"] = "Активна: {0}",
            ["tip.refresh"] = "Обновить использование",
            ["tip.settings"] = "Настройки",
            ["tip.more"] = "Ещё",
            ["card.switch"] = "Сменить",
            ["card.active"] = "Активна",
            ["usage.fiveHour"] = "5 часов",
            ["usage.sevenDay"] = "7 дней",
            ["usage.tooltip"] = "Реальное использование подписки — из того же источника, что и команда /usage в Claude Code (api.anthropic.com/api/oauth/usage). Учитывает использование на всех устройствах.\n\nВ реальном времени обновляется только активная учётная запись; остальные показывают значение с момента последней активности. Если данные недоступны, процент не показывается.",
            ["usage.fetching"] = "получение данных…",
            ["usage.updatesOnSwitch"] = "обновится при переключении",
            ["usage.justNow"] = "только что",
            ["usage.minAgo"] = "{0} мин назад",
            ["usage.hourAgo"] = "{0} ч назад",
            ["usage.dayAgo"] = "{0} дн назад",
            ["usage.updatedPrefix"] = "обновлено {0}",
            ["usage.resetting"] = "сброс…",
            ["usage.resetsInHM"] = "через {0} ч {1} мин",
            ["usage.resetsInM"] = "через {0} мин",
            ["usage.resetsPrefix"] = "сброс {0}",
            ["status.ready"] = "Готово",
            ["status.tokenWillRefresh"] = "Токен обновится",
            ["reauth.subtitle"] = "⚠ Вход устарел — исправьте через «+ Добавить аккаунт»",
            ["empty.title"] = "Пока нет сохранённых аккаунтов",
            ["empty.body"] = "Сохраните текущий аккаунт, затем добавьте ещё один, чтобы переключаться между ними.",
            ["footer.saveCurrent"] = "Сохранить текущий аккаунт",
            ["footer.addAccount"] = "+ Добавить аккаунт",
            ["footer.cancel"] = "Отмена",
            ["code.title"] = "Вставьте код авторизации",
            ["code.body"] = "После нажатия Authorize в браузере вставьте сюда код со страницы. Это не 6-значный код из письма.",
            ["code.submit"] = "Отправить",
            ["menu.rename"] = "Переименовать",
            ["menu.refreshTokens"] = "Обновить токены этого аккаунта",
            ["menu.refreshTokensTip"] = "Только активный аккаунт: перезаписывает актуальные токены в профиль.",
            ["menu.delete"] = "Удалить профиль",
            ["dialog.rename.label"] = "Отображаемое имя",
            ["common.cancel"] = "Отмена",
            ["common.save"] = "Сохранить",
            ["tray.noAccounts"] = "Нет сохранённых аккаунтов",
            ["tray.manage"] = "Управление аккаунтами…",
            ["tray.exit"] = "Выход",
            ["settings.title"] = "Настройки",
            ["settings.appearance"] = "ВНЕШНИЙ ВИД",
            ["settings.darkMode"] = "Тёмная тема",
            ["settings.darkModeDesc"] = "Использовать тёмное оформление.",
            ["settings.compact"] = "Компактный режим",
            ["settings.compactDesc"] = "Скрыть детали использования для плотного списка.",
            ["settings.language"] = "ЯЗЫК",
            ["settings.languageDesc"] = "Язык интерфейса.",
            ["settings.done"] = "Готово",
        },

        ["zh"] = new()
        {
            ["app.loading"] = "加载中…",
            ["app.notSignedIn"] = "未登录",
            ["app.activePrefix"] = "当前：{0}",
            ["tip.refresh"] = "刷新用量",
            ["tip.settings"] = "设置",
            ["tip.more"] = "更多",
            ["card.switch"] = "切换",
            ["card.active"] = "使用中",
            ["usage.fiveHour"] = "5 小时",
            ["usage.sevenDay"] = "7 天",
            ["usage.tooltip"] = "真实的订阅用量——与 Claude Code 的 /usage 命令来自同一来源（api.anthropic.com/api/oauth/usage），涵盖所有设备的用量。\n\n仅当前账户实时更新；其他账户显示上次活跃时的数值。若无法获取数据，则不显示百分比。",
            ["usage.fetching"] = "正在获取用量…",
            ["usage.updatesOnSwitch"] = "切换后更新",
            ["usage.justNow"] = "刚刚",
            ["usage.minAgo"] = "{0} 分钟前",
            ["usage.hourAgo"] = "{0} 小时前",
            ["usage.dayAgo"] = "{0} 天前",
            ["usage.updatedPrefix"] = "更新于 {0}",
            ["usage.resetting"] = "正在重置…",
            ["usage.resetsInHM"] = "{0} 小时 {1} 分钟后",
            ["usage.resetsInM"] = "{0} 分钟后",
            ["usage.resetsPrefix"] = "重置：{0}",
            ["status.ready"] = "就绪",
            ["status.tokenWillRefresh"] = "令牌将刷新",
            ["reauth.subtitle"] = "⚠ 登录已过期 — 请用“+ 添加账户”修复",
            ["empty.title"] = "尚无已保存的账户",
            ["empty.body"] = "保存当前登录的账户，再添加另一个即可在它们之间切换。",
            ["footer.saveCurrent"] = "保存当前账户",
            ["footer.addAccount"] = "+ 添加账户",
            ["footer.cancel"] = "取消",
            ["code.title"] = "粘贴授权码",
            ["code.body"] = "在浏览器中点击 Authorize 后，将页面上显示的代码粘贴到此处。这不是邮件中的 6 位验证码。",
            ["code.submit"] = "提交",
            ["menu.rename"] = "重命名",
            ["menu.refreshTokens"] = "刷新此账户的令牌",
            ["menu.refreshTokensTip"] = "仅限当前账户：将实时令牌重新写入配置。",
            ["menu.delete"] = "删除配置",
            ["dialog.rename.label"] = "显示名称",
            ["common.cancel"] = "取消",
            ["common.save"] = "保存",
            ["tray.noAccounts"] = "没有已保存的账户",
            ["tray.manage"] = "管理账户…",
            ["tray.exit"] = "退出",
            ["settings.title"] = "设置",
            ["settings.appearance"] = "外观",
            ["settings.darkMode"] = "深色模式",
            ["settings.darkModeDesc"] = "使用深色主题。",
            ["settings.compact"] = "紧凑模式",
            ["settings.compactDesc"] = "隐藏用量详情以获得更紧凑的列表。",
            ["settings.language"] = "语言",
            ["settings.languageDesc"] = "界面语言。",
            ["settings.done"] = "完成",
        },
    };
}
